[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.qmlls]
command = "qmlls"
args = [ "-E" ]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "qml"
language-servers = [ "qmlls" ]

[[language]]
name = "python"
language-servers = [ "basedpyright" ]
